PROJECT_ROOT_DIR=/root/lxf/se
BASE_COMPLIE_FILES=$(PROJECT_ROOT_DIR)/base/time_stamp.cc
COMPLIE_OPTION= -Wall -Werror

all:
	g++ test_singleton.cc $(BASE_COMPLIE_FILES) -g -o test_singleton.out -I $(PROJECT_ROOT_DIR) $(COMPLIE_OPTION) -lpthread
