PROJECT_ROOT_DIR=/root/lxf/se
COMPLIE_OPTION= -Wall -Werror

all:
	g++ test_sock_addr.cc	$(PROJECT_ROOT_DIR)/net/sock_addr.cc $(PROJECT_ROOT_DIR)/base/time_stamp.cc -I $(PROJECT_ROOT_DIR) -g -o test_sock_addr.out $(COMPLIE_OPTION)
